# Python Basics


## Variables and Data Types

In [12]:
# Define variables
x = 10          # Integer
pi = 3.14       # Float
name = "Alice"  # String
is_student = True  # Boolean

# Print variables
print("x:", x)
print("pi:", pi)
print("name:", name)
print("is_student:", is_student)

# Check data types
print(type(x))
print(type(pi))
print(type(name))
print(type(is_student))

# List, Tuple, Dictionary, Set
my_list = [1, 2, 3, 4]
my_tuple = (5, 6, 7, 8)
my_dict = {"key1": "value1", "key2": "value2"}
my_set = {9, 10, 11}

print("List:", my_list)
print("Tuple:", my_tuple)
print("Dictionary:", my_dict)
print("Set:", my_set)

x: 10
pi: 3.14
name: Alice
is_student: True
<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>
List: [1, 2, 3, 4]
Tuple: (5, 6, 7, 8)
Dictionary: {'key1': 'value1', 'key2': 'value2'}
Set: {9, 10, 11}


## Conditional Statements (if-else)


In [13]:
# Example of if-else
x = 15
if x > 10:
    print("x is greater than 10")
elif x == 10:
    print("x is equal to 10")
else:
    print("x is less than 10")

x is greater than 10


## Loops

In [14]:
## Loops

# For loop example
for i in range(5):
    print("For loop iteration:", i)

# While loop example
counter = 0
while counter < 5:
    print("While loop iteration:", counter)
    counter += 1

For loop iteration: 0
For loop iteration: 1
For loop iteration: 2
For loop iteration: 3
For loop iteration: 4
While loop iteration: 0
While loop iteration: 1
While loop iteration: 2
While loop iteration: 3
While loop iteration: 4


## Functions

In [15]:
# Define a simple function
def greet(name):
    return f"Hello, {name}!"

# Test the function
print(greet("Alice"))

Hello, Alice!


## Run a script

In [16]:
# Example of writing a script (this part would normally go in a .py file)
# Save this content as script.py
# Then run it in the terminal with: python script.py
if __name__ == "__main__":
    print("This script is being run directly.")

This script is being run directly.


# Python Libraries for Data Analysis: Numpy

In [17]:
# Importing the NumPy library
import numpy as np

## 1. Create Arrays

In [18]:
# Creating a 1D array
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d)

1D Array: [1 2 3 4 5]


In [19]:
# Creating a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:\n", array_2d)


2D Array:
 [[1 2 3]
 [4 5 6]]


In [20]:
# Creating arrays with zeros, ones, or a range of numbers
zeros_array = np.zeros((2, 3))
ones_array = np.ones((3, 2))
range_array = np.arange(0, 10, 2)
print("\nZeros Array:\n", zeros_array)
print("\nOnes Array:\n", ones_array)
print("\nRange Array:", range_array)


Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]

Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

Range Array: [0 2 4 6 8]


## 2. Array Operations

In [21]:
# Element-wise addition, subtraction, multiplication, and division
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])
print("\nAddition:", array_a + array_b)
print("Multiplication:", array_a * array_b)


Addition: [5 7 9]
Multiplication: [ 4 10 18]


In [22]:
# Dot product
dot_product = np.dot(array_a, array_b)
print("\nDot Product:", dot_product)


Dot Product: 32


## 3. Statistical Functions

In [23]:
array_stats = np.array([10, 20, 30, 40, 50])
print("\nMean:", np.mean(array_stats))
print("Sum:", np.sum(array_stats))
print("Maximum:", np.max(array_stats))
print("Standard Deviation:", np.std(array_stats))


Mean: 30.0
Sum: 150
Maximum: 50
Standard Deviation: 14.142135623730951


## 4. Indexing and Slicing

In [24]:
print("\nElement at index 1:", array_1d[1])  # Accessing element
print("First row of 2D array:", array_2d[0])  # Accessing a row
print("Element at (1, 2):", array_2d[1, 2])  # Accessing specific element


Element at index 1: 2
First row of 2D array: [1 2 3]
Element at (1, 2): 6


## 5. Reshaping Arrays

In [25]:
reshaped_array = np.reshape(array_1d, (1, 5))  # Reshape to 1 row, 5 columns
print("\nReshaped Array:\n", reshaped_array)


Reshaped Array:
 [[1 2 3 4 5]]


## 6. Boolean Indexing

In [26]:
bool_array = array_stats > 25  # Elements greater than 25
print("\nBoolean Array:", bool_array)
print("Filtered Array (values > 25):", array_stats[bool_array])


Boolean Array: [False False  True  True  True]
Filtered Array (values > 25): [30 40 50]


# Python Libraries for Data Analysis: Pandas

In [27]:
# Importing the Pandas library
import pandas as pd

## 1. Creating a DataFrame

In [28]:
# Creating a DataFrame from a dictionary
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "City": ["New York", "Los Angeles", "Chicago"]
}
df = pd.DataFrame(data)
print("DataFrame:\n", df)

DataFrame:
       Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago


## 2. Reading and Writing Files

In [29]:
# Save the DataFrame to a CSV file
df.to_csv("example.csv", index=False)
print("\nData saved to 'example.csv'")

# Read the CSV file back into a DataFrame
df_read = pd.read_csv("example.csv")
print("\nRead DataFrame from CSV:\n", df_read)


Data saved to 'example.csv'

Read DataFrame from CSV:
       Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago


## 3. Basic DataFrame Operations


In [30]:
print("\nColumn Names:", df.columns)
print("Data Types:\n", df.dtypes)
print("First 2 Rows:\n", df.head(2))  # Display the first 2 rows


Column Names: Index(['Name', 'Age', 'City'], dtype='object')
Data Types:
 Name    object
Age      int64
City    object
dtype: object
First 2 Rows:
     Name  Age         City
0  Alice   25     New York
1    Bob   30  Los Angeles
